#!/usr/bin/env python

# import the neccessary repo
import sys
import rospy
import actionlib

# Joint-Based Controller
from control_msgs.msg import FollowJointTrajectoryAction, FollowJointTrajectoryGoal
from trajectory_msgs.msg import JointTrajectoryPoint

# Controller Manager
from controller_manager_msgs.srv import SwitchControllerRequest, SwitchController
from controller_manager_msgs.srv import LoadControllerRequest, LoadController
from controller_manager_msgs.srv import ListControllers, ListControllersRequest

# Cartesian-Based Controller
import geometry_msgs.msg as geometry_msgs
from cartesian_control_msgs.msg import (
    FollowCartesianTrajectoryAction,
    FollowCartesianTrajectoryGoal,
    CartesianTrajectoryPoint,
)

# Compatibility for python2 and python3
if sys.version_info[0] < 3:
    input = raw_input

# If your robot description is created with a tf_prefix, those would have to be adapted
JOINT_NAMES = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]

# All of those controllers can be used to execute joint-based trajectories.
# The scaled versions should be preferred over the non-scaled versions.
JOINT_TRAJECTORY_CONTROLLERS = [
    "scaled_pos_joint_traj_controller",
    "scaled_vel_joint_traj_controller",
    "pos_joint_traj_controller",
    "vel_joint_traj_controller",
    "forward_joint_traj_controller",
]
JOINT_CONTROLLER_SELLECT = 0
"""
🔥scaled_pos_joint_traj_controller🔥 : 
    It controls the movement of each joint to follow a desired position trajectory, with an added scaling factor to modulate the speed and smoothness of the motion.
scaled_vel_joint_traj_controller : 
    It controls the velocity of each joint to follow a desired velocity trajectory, with a scaling factor to adjust the speed of the movements.
pos_joint_traj_controller : 
    It controls each joint to follow a specified position trajectory directly, without any additional scaling factors.
vel_joint_traj_controller : 
    It directly controls the velocity of each joint to follow a specified velocity trajectory, without any scaling factors.
forward_joint_traj_controller : 
    It uses a predefined joint trajectory to generate control inputs directly, often without relying heavily on feedback.
"""

# All of those controllers can be used to execute Cartesian trajectories.
# The scaled versions should be preferred over the non-scaled versions.
CARTESIAN_TRAJECTORY_CONTROLLERS = [
    "pose_based_cartesian_traj_controller",
    "joint_based_cartesian_traj_controller",
    "forward_cartesian_traj_controller",
]
CARTESIAN_CONTROLLER_SELLECT = 0
"""
🔥pose_based_cartesian_traj_controller🔥 : 
    It calculates the difference between the current pose and the target pose, 
    generating the necessary control inputs to gradually move the robot's end-effector (typically the Tool Center Point, TCP) to the desired pose.
joint_based_cartesian_traj_controller : 
    Given a Cartesian trajectory, it computes the desired positions for each joint to move the end-effector along the specified Cartesian path. 
    It combines inverse kinematics solving and trajectory tracking.
forward_cartesian_traj_controller : 
    It generates control inputs based on a predetermined Cartesian trajectory, driving the end-effector along the path directly,
    usually without using sensor feedback to adjust the trajectory.
"""

# We'll have to make sure that none of these controllers are running, as they will
# be conflicting with the joint trajectory controllers
CONFLICTING_CONTROLLERS = ["joint_group_vel_controller", "twist_controller"]
"""
joint_group_vel_controller : 
    It sets the velocity for each joint in the specified group, allowing for coordinated movement based on the desired velocity inputs.
twist_controller : 
    It commands the end-effector to move with specified linear and angular velocities, typically used for direct teleoperation or Cartesian space control.
"""


class MotionCommander:
    """Small trajectory client to test a joint trajectory"""

    ###################### send the joint trajectory ######################
    def __init__(self, 
                 verbose: bool = True, 
                 timeout_wait_duration: int=5,
                 joint_controller_index: int = JOINT_CONTROLLER_SELLECT, 
                 cartesian_controller_index: int = CARTESIAN_CONTROLLER_SELLECT):
        
        # params initialization
        self.is_verbose = verbose
        self.wait_duration = timeout_wait_duration
        
        # initialize a node
        rospy.init_node("motion_commander")
        timeout = rospy.Duration(self.wait_duration)

        # 
        self.switch_srv = rospy.ServiceProxy("controller_manager/switch_controller", SwitchController)
        self.load_srv = rospy.ServiceProxy("controller_manager/load_controller", LoadController)
        self.list_srv = rospy.ServiceProxy("controller_manager/list_controllers", ListControllers)
        
        # 
        try:
            self.switch_srv.wait_for_service(timeout.to_sec()) # wait for the service 
        except rospy.exceptions.ROSException as err:
            rospy.logerr("Could not reach controller switch service. Msg: {}".format(err))
            sys.exit(-1)

        # initialize the robot controller | joint_trajectory_controller or cartesian_trajectory_controller
        self.joint_trajectory_controller = JOINT_TRAJECTORY_CONTROLLERS[joint_controller_index]
        self.cartesian_trajectory_controller = CARTESIAN_TRAJECTORY_CONTROLLERS[cartesian_controller_index]




    ###################### 🔥send the joint trajectory🔥 ######################
    def send_joint_trajectory(self, position_list=[], velocity_list=[], duration_list=[]):
        """Send a trajectory using the selected action server"""

        # switch the controller to what we chose
        self.switch_controller(self.joint_trajectory_controller)

        # initialize a joint traj client
        trajectory_client = actionlib.SimpleActionClient(
            "{}/follow_joint_trajectory".format(self.joint_trajectory_controller), # the name of the server in ROS network
            FollowJointTrajectoryAction, # the type of the message
        )

        # wait for action server to be ready
        timeout = rospy.Duration(self.wait_duration)
        if not trajectory_client.wait_for_server(timeout):
            rospy.logerr("Could not reach controller action server.")
            sys.exit(-1)

        # create trajectory goal
        goal = FollowJointTrajectoryGoal()
        
        # name the each joint
        goal.trajectory.joint_names = JOINT_NAMES
        
        # check the size of each list in the trajectory
        assert len(position_list)==len(velocity_list)==len(duration_list), "[ERROR] receive different sizes of each list in joint trajectory"
        
        # append the joint-based trajectory 
        for i, position in enumerate(position_list):
            point = JointTrajectoryPoint()
            point.positions = position
            point.velocities = velocity_list[i]
            point.time_from_start = rospy.Duration(duration_list[i])
            goal.trajectory.points.append(point)
    
        # ask the user to confitm the following actions
        if self.is_verbose:
            self.ask_confirmation(position_list)
            rospy.loginfo("Executing trajectory using the {}".format(self.joint_trajectory_controller))

        # send the goals and wait for answer
        trajectory_client.send_goal(goal)
        trajectory_client.wait_for_result()

        # get the results from server
        result = trajectory_client.get_result()
        rospy.loginfo("Trajectory execution finished in state {}".format(result.error_code))
    
    ###################### 🔥send the cartesian trajectory🔥 ######################
    def send_cartesian_trajectory(self, pose_list=[], duration_list=[]):
        """Send a Cartesian trajectory it using the selected action server"""

        # switch to the controller that we chose
        self.switch_controller(self.cartesian_trajectory_controller)

        # create the cartesian goal
        goal = FollowCartesianTrajectoryGoal()

        # initialize the trajectory client
        trajectory_client = actionlib.SimpleActionClient(
            "{}/follow_cartesian_trajectory".format(self.cartesian_trajectory_controller), # the name of the server in ROS network
            FollowCartesianTrajectoryAction, # the type of the message
        )

        # wait for action server to be ready
        timeout = rospy.Duration(self.wait_duration)
        if not trajectory_client.wait_for_server(timeout):
            rospy.logerr("Could not reach controller action server.")
            sys.exit(-1)
        
        # check the size of each list in the trajectory
        assert len(pose_list)==len(duration_list), "[ERROR] receive different sizes of each list in pose trajectory"

        # append the cartesian-based trajectory 
        for i, pose in enumerate(pose_list):
            point = CartesianTrajectoryPoint()
            point.pose = pose
            point.time_from_start = rospy.Duration(duration_list[i])
            goal.trajectory.points.append(point)
        
        # ask the user to confitm the following actions
        if self.is_verbose:
            self.ask_confirmation(pose_list)
            rospy.loginfo("Executing trajectory using the {}".format(self.cartesian_trajectory_controller))

        # send the goals and wait for answer
        trajectory_client.send_goal(goal)
        trajectory_client.wait_for_result()

        # get the results from server
        result = trajectory_client.get_result()
        rospy.loginfo("Trajectory execution finished in state {}".format(result.error_code))

    def ask_confirmation(self, waypoint_list):
        """Ask the user for confirmation. This function is obviously not necessary, but makes sense
        in a testing script when you know nothing about the user's setup."""

        rospy.logwarn("The robot will move to the following waypoints: \n{}".format(waypoint_list))
        confirmed = False
        valid = False
        while not valid:
            input_str = input(
                "Please confirm that the robot path is clear of obstacles.\n"
                "Keep the EM-Stop available at all times. You are executing\n"
                "the motion at your own risk. Please type 'y' to proceed or 'n' to abort: "
            )

            valid = input_str in ["y", "n"]

            if not valid:
                rospy.loginfo("Please confirm by entering 'y' or abort by entering 'n'")
            else:
                confirmed = input_str == "y"
        
        if not confirmed:
            rospy.loginfo("Exiting as requested by user.")
            sys.exit(0)
        
    def switch_controller(self, target_controller):
        """Activates the desired controller and stops all others from the predefined list above"""
    
        # all of the controllers
        other_controllers = (
            JOINT_TRAJECTORY_CONTROLLERS
            + CARTESIAN_TRAJECTORY_CONTROLLERS
            + CONFLICTING_CONTROLLERS
        )
        other_controllers.remove(target_controller)

        # check whether the target controller is running
        srv = ListControllersRequest()
        response = self.list_srv(srv)
        for controller in response.controller:
            if controller.name == target_controller and controller.state == "running":
                return

        # load the target controller if it's not already loaded
        srv = LoadControllerRequest()
        srv.name = target_controller
        self.load_srv(srv)

        # start the target_controller and stop the other controllers
        srv = SwitchControllerRequest()
        srv.stop_controllers = other_controllers
        srv.start_controllers = [target_controller]
        srv.strictness = SwitchControllerRequest.BEST_EFFORT
        self.switch_srv(srv)




if __name__ == "__main__":

    client = MotionCommander()
    
    # # JOINT TRAJECTORY CONTROLLER
    # # the following list are arbitrary positions | Change to your own needs if desired
    # position_list = [[0, -1.57, -1.57, 0, 0, 0]]
    # position_list.append([0.2, -1.57, -1.57, 0, 0, 0])
    # position_list.append([-0.5, -1.57, -1.2, 0, 0, 0])
    # velocity_list = [[0.2, 0, 0, 0, 0, 0]]
    # velocity_list.append([-0.2, 0, 0, 0, 0, 0])
    # velocity_list.append([0, 0, 0, 0, 0, 0])
    # duration_list = [3.0, 7.0, 10.0]
    # client.send_joint_trajectory(position_list, velocity_list, duration_list)
    
    # # POSE TRAJECTORY CONTROLLER
    # # the following list are arbitrary positions | Change to your own needs if desired | Position([3]) + Quaternion([4])
    # pose_list = [
    #     geometry_msgs.Pose(
    #         geometry_msgs.Vector3(0.4, -0.1, 0.4), geometry_msgs.Quaternion(0, 0, 0, 1)
    #     ),
    #     geometry_msgs.Pose(
    #         geometry_msgs.Vector3(0.4, -0.1, 0.6), geometry_msgs.Quaternion(0, 0, 0, 1)
    #     ),
    #     geometry_msgs.Pose(
    #         geometry_msgs.Vector3(0.4, 0.3, 0.6), geometry_msgs.Quaternion(0, 0, 0, 1)
    #     ),
    #     geometry_msgs.Pose(
    #         geometry_msgs.Vector3(0.4, 0.3, 0.4), geometry_msgs.Quaternion(0, 0, 0, 1)
    #     ),
    #     geometry_msgs.Pose(
    #         geometry_msgs.Vector3(0.4, -0.1, 0.4), geometry_msgs.Quaternion(0, 0, 0, 1)
    #     ),
    # ]
    # duration_list = [3.0, 4.0, 5.0, 6.0, 7.0]
    # client.send_cartesian_trajectory(pose_list, duration_list)

    # raise ValueError(
    #     "I only understand types 'joint_based' and 'cartesian', but got '{}'".format(
    #         trajectory_type
    #     )
    # )


